package ui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Shimanta
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        lbl_u.setVisible(false);
        lbl_p.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtLogin = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jShowpass = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        lbl_p = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hmslogo.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" HOSTEL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jUsername.setBackground(new java.awt.Color(204, 204, 204));
        jUsername.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jUsername.setForeground(new java.awt.Color(51, 51, 51));
        jUsername.setText("username");
        jUsername.setBorder(null);
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
        });
        jPanel3.add(jUsername);
        jUsername.setBounds(134, 135, 260, 42);

        jPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPassword.setText("password");
        jPassword.setBorder(null);
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jPassword);
        jPassword.setBounds(130, 200, 270, 40);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(130, 180, 260, 10);

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(130, 240, 260, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 150, 30, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passwordicon2.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 210, 30, 30);

        jbtLogin.setBackground(new java.awt.Color(255, 255, 255));
        jbtLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jbtLogin.setText("LOG IN");
        jbtLogin.setBorder(null);
        jbtLogin.setBorderPainted(false);
        jbtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtLoginMouseEntered(evt);
            }
        });
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtLogin);
        jbtLogin.setBounds(290, 330, 100, 40);

        jbtCancel.setBackground(new java.awt.Color(255, 255, 255));
        jbtCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jbtCancel.setText("CANCEL");
        jbtCancel.setBorder(null);
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jbtCancel);
        jbtCancel.setBounds(120, 330, 100, 40);

        jShowpass.setBackground(new java.awt.Color(204, 204, 204));
        jShowpass.setForeground(new java.awt.Color(51, 51, 51));
        jShowpass.setText("Show Password");
        jShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowpassActionPerformed(evt);
            }
        });
        jPanel3.add(jShowpass);
        jShowpass.setBounds(130, 260, 190, 29);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CLOSE.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(430, 0, 40, 40);

        lbl_u.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_u.setForeground(new java.awt.Color(255, 51, 0));
        lbl_u.setText("*");
        jPanel3.add(lbl_u);
        lbl_u.setBounds(400, 150, 20, 20);

        lbl_p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_p.setForeground(new java.awt.Color(255, 51, 0));
        lbl_p.setText("*");
        jPanel3.add(lbl_p);
        lbl_p.setBounds(400, 220, 20, 22);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
           lbl_u.setVisible(false);
        lbl_p.setVisible(false);
       if(jUsername.getText().length()!=0 && jPassword.getText().length()!=0){
          
           if(jUsername.getText().equals("hostel") && jPassword.getText().equals("1234")){
               this.dispose();
               new HomePage().setVisible(true);
           }
           else{
               JOptionPane.showMessageDialog(this, "Username or Password is incorrect!");
           }
       }
       if(jUsername.getText().equals("")){
           lbl_u.setVisible(true);
           JOptionPane.showMessageDialog(this, "Username or Password can not be empty!");
       }
       if(jPassword.getText().equals("")){
           lbl_p.setVisible(true);
           
       }
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
      
       /* lbl_u.setVisible(false);
        lbl_p.setVisible(false);
        
        if(jUsername.getText().equals("")){
            lbl_u.setVisible(true);
        }
        if(String.valueOf(jPassword.getPassword()).equals("")){
            lbl_p.setVisible(true);
        }
        if(jUsername.getText().equals("hostel") && jPassword.getPassword().equals("admin")){
            setVisible(false);
            new HomePage().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Enter correct username or password");
        }*/
       
        lbl_u.setVisible(false);
        lbl_p.setVisible(false);
       if(jUsername.getText().length()!=0 && jPassword.getText().length()!=0){
          
           if(jUsername.getText().equals("hostel") && jPassword.getText().equals("1234")){
               this.dispose();
               new HomePage().setVisible(true);
           }
           else{
               JOptionPane.showMessageDialog(this, "Username or Password is incorrect!");
           }
       }
       if(jUsername.getText().equals("")){
           lbl_u.setVisible(true);
           JOptionPane.showMessageDialog(this, "Username or Password can not be empty!");
       }
       if(jPassword.getText().equals("")){
           lbl_p.setVisible(true);
           
       }
       /*else{
           lbl_u.setVisible(true);
           lbl_p.setVisible(true);
           JOptionPane.showMessageDialog(this,"Username or Password can not be empty!");
       }*/
    }//GEN-LAST:event_jbtLoginActionPerformed

    private void jbtLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtLoginMouseEntered
        
    }//GEN-LAST:event_jbtLoginMouseEntered

    private void jShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowpassActionPerformed
        if(jShowpass.isSelected()){
            jPassword.setEchoChar((char)0);
        }
        else{
            jPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jShowpassActionPerformed

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        jUsername.setText("");
    }//GEN-LAST:event_jUsernameFocusGained

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        jPassword.setText("");
    }//GEN-LAST:event_jPasswordFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to exist?","select",
                JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
    } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
}
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jShowpass;
    private javax.swing.JTextField jUsername;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtLogin;
    private javax.swing.JLabel lbl_p;
    private javax.swing.JLabel lbl_u;
    // End of variables declaration//GEN-END:variables
}
